ANDROID: fix bogomips reporting in /proc/cpuinfo
Add missing <linux/delay.h> to fix following compilation error:

arch/arm64/kernel/cpuinfo.c: In function 'c_show':
arch/arm64/kernel/cpuinfo.c:117:7: error: 'loops_per_jiffy' undeclared (first use in this function)
       loops_per_jiffy / (500000UL/HZ),
       ^
arch/arm64/kernel/cpuinfo.c:117:7: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:257: recipe for target 'arch/arm64/kernel/cpuinfo.o' failed
make[1]: *** [arch/arm64/kernel/cpuinfo.o] Error 1
Makefile:948: recipe for target 'arch/arm64/kernel' failed

Fixes: b4cd3c9de25b ("BACKPORT: arm64: Move /proc/cpuinfo handling code")
Fixes: AOSP Change-Id: I98624593273ae4c90ae299f063d26f35a39a0a31
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>